docs: product managements guide
clouway/docs.clouway.com pull request #1
Opened 2019-07-16 06:25 UTC by p-nedelchev

Guide for managing products, variants and packs.
![image](https://user-images.githubusercontent.com/20314059/61270651-fba9d100-a7aa-11e9-80cf-776b11e10677.png)
![image](https://user-images.githubusercontent.com/20314059/61270672-082e2980-a7ab-11e9-84ad-f23fd0c169a7.png)
![image](https://user-images.githubusercontent.com/20314059/61270842-868acb80-a7ab-11e9-9b17-2d9b8beddaf3.png)

2019-07-16 06:39 UTC, mgenov commented on src/pages/politis/guide/product_management/register-product.bg.md
> +При успешно натискане на бутона се зарежда форма за нов продукт
След натискане на бутона

2019-07-16 06:40 UTC, p-nedelchev commented on src/pages/politis/guide/product_management/register-product.bg.md
> +При успешно натискане на бутона се зарежда форма за нов продукт
Corrected.

2019-07-16 06:44 UTC, mgenov requested changes

2019-07-16 06:44 UTC, mgenov commented on src/pages/politis/guide/product_management/register-product.bg.md
> +В края на формата има две опции за новия продукт:
Регистрацията на нов продукт ви дава възможност за попълните следните опции:

Note: The product form has more than 2 options and we have to add a description for all fields.

2019-07-16 09:08 UTC, p-nedelchev commented on src/pages/politis/guide/product_management/register-product.bg.md
> +В края на формата има две опции за новия продукт:
Description for all field of new products, variant and pack forms have been added.

2019-07-16 09:27 UTC, mgenov commented on src/pages/politis/guide/product_management/register-product.bg.md
> +* **Проследяване на партиди** - тази опция е подходяща за продукти, чиято партита трябва да може да бъде проследена в различните етапи на продуктообмена.
typo: партида

2019-07-16 09:29 UTC, mgenov commented on src/pages/politis/guide/product_management/register-product.bg.md
> +**Важно!** - за да бъде успешно изтриването на варианта трябва първо да се изтрият всички създадени пакети към този вариант и наличностите във всички работни обекти за този вариант да са нулеви!
**Забележка:** - изтриването на вариант или опаковка изисква да няма наличности в складовете.

2019-07-16 09:35 UTC, mgenov commented on src/pages/politis/guide/product_management/register-product.bg.md
> +### Продукти
Here we can add some description for the products.  

For example:
"Each product can contain seperate variants with product options such as weight, size and color, as well as composite variants and pack sizes."

2019-07-16 10:50 UTC, mgenov commented on src/pages/politis/guide/product_management/register-product.bg.md
> +* **Мерна единица** - основната мерна единица, в която се измерва продукта - грам (гр.), брой (бр.) и т.н. Това поле е *задължително*.
грам (гр.), брой (бр.) и др.

2019-07-16 13:06 UTC, p-nedelchev commented on src/pages/politis/guide/product_management/register-product.bg.md
> +### Продукти
Short product description added: `Всеки продукт в Политис съдържа информация за име, тип, мерна единица, доставчик. Към продуктите могат да се създават варианти, а самите варианти да се организират в опаковки. Всеки продукт може да бъде зачислен към определена дивизия за по-лесна обработка  и ценообразуване.`

2019-07-16 13:07 UTC, p-nedelchev commented on src/pages/politis/guide/product_management/register-product.bg.md
> +### Продукти
Short variant description added: `Към всеки продукт може да се добавят различни варианти. Всеки вариант съдържа информация за име, SKU, цени. Вариантите могат да се организират в опаковки.`

2019-07-16 13:07 UTC, p-nedelchev commented on src/pages/politis/guide/product_management/register-product.bg.md
> +* **Проследяване на партиди** - тази опция е подходяща за продукти, чиято партита трябва да може да бъде проследена в различните етапи на продуктообмена.
Typo fixed.

2019-07-16 13:08 UTC, p-nedelchev commented on src/pages/politis/guide/product_management/register-product.bg.md
> +**Важно!** - за да бъде успешно изтриването на варианта трябва първо да се изтрият всички създадени пакети към този вариант и наличностите във всички работни обекти за този вариант да са нулеви!
Changed as suggested.

2019-07-16 13:08 UTC, p-nedelchev commented on src/pages/politis/guide/product_management/register-product.bg.md
> +* **Мерна единица** - основната мерна единица, в която се измерва продукта - грам (гр.), брой (бр.) и т.н. Това поле е *задължително*.
space removed.

2019-07-17 19:51 UTC, mgenov approved these changes
LGTM!

2019-07-17 19:52 UTC, merged